[model]
name = "openrouter/free"
# same as
# {
#   "model": {
#     "name": "openrouter/free"
#   }
# }
cwd = "/Users/dhwanil/Desktop/agentic-cli"

[mcp_servers.filesystem]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-filesystem",
    "/Users/dhwanil/Desktop/agentic-cli",
    "/tmp",
]

[mcp_servers.github]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-github"]
# mcp_servers.github.env
env = { GITHUB_TOKEN = "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" }

# same as
# . creates a nested dictionary
# { 
#   "mcp_servers": { # variable in config
#     "github": {
#       this all is MCPServerConfig object dict[str, MCPServerConfig]
#       "command": "npx",
#       "args": ["-y", "@modelcontextprotocol/server-github"],
#       "env": {
#         "GITHUB_TOKEN": ...
#       }
#     }
#   }
# }

[[hooks]]
name = "test_before_tool"
trigger = "before_tool"
command = "python3 ./scripts/test_tool.py"
